version: '3.8'

services:
  db:
    image: mariadb:10.4 
    container_name: mydb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_USER: root
      MYSQL_DATABASE: customer_service
      # MYSQL_USER: ds
      MYSQL_PASSWORD: root
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    networks:
      - myapi
    volumes:
      - ./data:/var/lib/mysql

  web:
    build: ./app
    container_name: service_customer
    volumes:
      - ./app:/app
    ports:
      - "5001:80"
    networks:
      - myapi
    depends_on:
      - db

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: root
        PMA_PHPMYADMIN_CHARSET: utf8mb4
        PMA_PHPMYADMIN_LANG: thai
      ports:
        - "8181:80"
      networks:
        - myapi

volumes:
  db_data:
networks:
  myapi:
